# Header
menu:
  Home: /
  Archives: /archives
  #About: /about.html

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: Here is tobeytang's blog, which records every bit of life and shares daily life.

# Theme Secondary subtitle
susbtitle_secondary: We are young and far from old. Sensible is too heavy, there are many things we can only do now. So get rid of the shackles and move towards freedom.

# Footer About Section
about_footer: Here is tobeytang's blog, which records every bit of life and shares daily life.

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: klugjo
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/txlvj
#facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/txlvj/
#dribble_url: \#
github_url: https://github.com/tobeytang123
#googleplus_url: \#
behance_url: https://www.behance.net/
#fivehundredpx_url: \#
email_url: https://tobeytang.netlify.app/771073163@qq.com
#rss_url: \#
